### ISSUE TITLE
Strange Window Bar Cropping

### ISSUE THREAD

**Issue by januwland** [JustinFincher/BoardForGitHub#13]
Happening on MacOS Mojave 10.14.2

Can't be fixed with any menubar or ui changes including the fullscreen button, toggling menu, reset system, etc.

<img width="1270" alt="screenshot 2019-01-09 10 58 33" src="https://user-images.githubusercontent.com/38091842/50866324-a1941180-13fd-11e9-904f-f740ee865c97.png">

**Comment by JustinFincher** [comment]
Sorry for this, I will look into this issue as soon as I finish my final exam (Jan 16), this might be a CSS related issue as GitHub updated their website.

**Comment by januwland** [comment]
Thanks! Otherwise, super cool app, good luck with the exam.
