### ISSUE TITLE
How to switch Project?

### ISSUE THREAD

**Issue by harryworld** [JustinFincher/BoardForGitHub#9]
I paid for the license as a support.
Curious how to switch to my own project, especially private one.

**Comment by JustinFincher** [comment]
Hi @harryworld , you can click the GitHub icon or go to file - open menu. If you still can't switch project, please contact me again. :-)

**Comment by JustinFincher** [comment]
And don't forget to press `Command + S` to save as the current board. Thank you for support Board For GitHub!

**Comment by harryworld** [comment]
Alright, not that intuitive, but works.
